Repository redBorder/cookbook-rb-events-counter, pull requests merged in 2024-06, with the labels that each got.

#3 fix curl
  resources/providers/config.rb
Labels: kind/bug, size/XS

#6 Improvement/fix lint
  resources/attributes/default.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: enhancement, kind/bug, lint, refactor, size/L

#7 Release 0.0.7
  .github/workflows/rpm.yml
  CHANGELOG.md
  README.md
  resources/attributes/default.rb
  resources/metadata.rb
  resources/providers/config.rb
  resources/recipes/default.rb
  resources/resources/config.rb
Labels: size/L, kind/documentation
